apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins

spec:
  replicas: 1

  selector:
    matchLabels:
      app: jenkins

  template:
    metadata:
      labels:
        app: jenkins

    spec:
      containers:

      - name: jenkins
        image: localhost:5001/my-jenkins-python:latest
        imagePullPolicy: Always

        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375

        ports:
        - containerPort: 8080
        - containerPort: 50000

        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home


      - name: docker
        image: docker:26-dind

        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""

        command:
        - dockerd
        - --host=tcp://0.0.0.0:2375
        - --host=unix:///var/run/docker.sock
        - --insecure-registry=host.docker.internal:5001

        securityContext:
          privileged: true

        volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker


      volumes:

      - name: jenkins-home
        emptyDir: {}

      - name: docker-storage
        emptyDir: {}